### ISSUE TITLE
我使用Alexey_yolov4+这个数据集，得到的结果如下，请问这是正常的么？

### ISSUE THREAD

**Issue by fusang1337** [gengyanlei/fire-smoke-detect-yolov4#31]
(next mAP calculation at 6175 iterations)
 Last accuracy mAP@0.50 = 62.27 %, best = 66.48 %
 6000: 1.022357, 1.471952 avg loss, 0.000010 rate, 4.679000 seconds, 192000 images, 0.091826 hours left
Resizing to initial size: 416 x 416  try to allocate additional workspace_size = 52.43 MB
 CUDA allocate done!

 calculation mAP (mean average precision)...
 Detection layer: 139 - type = 28
 Detection layer: 150 - type = 28
 Detection layer: 161 - type = 28
260
 detections_count = 1069, unique_truth_count = 413
class_id = 0, name = fire, ap = 61.61%           (TP = 258, FP = 106)

 for conf_thresh = 0.25, precision = 0.71, recall = 0.62, F1-score = 0.66
 for conf_thresh = 0.25, TP = 258, FP = 106, FN = 155, average IoU = 54.18 %

 IoU threshold = 50 %, used Area-Under-Curve for each unique Recall
 mean average precision (mAP@0.50) = 0.616056, or 61.61 %
Total Detection Time: 9 Seconds

感觉指标是不是有点低啊=-=
![chart_yolov4-fire](https://user-images.githubusercontent.com/17375049/128688262-317c8356-9fc6-41ed-9ea7-98920751d473.png)

**Comment by gengyanlei** [comment]
看实际效果，不惟精度论

**Comment by fusang1337** [comment]
实际测试了几个视频，主观上效果都挺不错的。但是不知道怎么量化指标，我想批量测试照片，然后得到指标，批量测试照片不知道怎么做=-=
