### ISSUE TITLE
数据集在哪下载呢？》

### ISSUE THREAD

**Issue by henbucuoshanghai** [gengyanlei/fire-smoke-detect-yolov4#36]
找了一下 没找到。

**Comment by henbucuoshanghai** [comment]
only fire in this dataset? where is smoke?

**Comment by gengyanlei** [comment]
![image](https://user-images.githubusercontent.com/22360785/139643333-cf5621e9-518f-4a39-a9f8-17dca2549cc5.png)
百度整理了一下

**Comment by henbucuoshanghai** [comment]
tks

**Comment by gengyanlei** [comment]
你其实没有仔细看readme，里面还有10000+的图像呢，可以自己标注；

**Comment by henbucuoshanghai** [comment]
&nbsp; I saw it,but I donot have enough time to label them
