### ISSUE TITLE
DJL调用best.pt的问题 

### ISSUE THREAD

**Issue by javadoge** [gengyanlei/fire-smoke-detect-yolov4#44]
best.pt 这是训练后的模型么？DLJ调用yolov5模型遇到一些问题

**Comment by javadoge** [comment]
有没有大佬 有 DJL 使用yolov5模型的例子？

我用python直接调用识别没问题，但是DJL使用yolov5模型 识别有问题呢，识别不了

代码如下：
`Translator<Image, DetectedObjects> translator =  YoloV5Translator
                .builder()
                .setPipeline(pipeline)
                .optSynset(Arrays.asList("fire"))
                .build();

        Criteria<Image, DetectedObjects> criteria = Criteria.builder()
                .setTypes(Image.class, DetectedObjects.class)
                .optModelUrls("build/yolov5/")
                .optModelName("firesmoke.torchscript")
                .optTranslator(translator)
                .optProgress(new ProgressBar())
                .build();`

效果如下：

![Uploading detected-DSC00020_0.png…]()

**Comment by gengyanlei** [comment]
这是yolov5 v3版本，我上传了对应的版本代码，你也可以去yolov5官方查看下载。

**Comment by javadoge** [comment]
@gengyanlei  大佬，没太明白什么意思，您意思git 代码这个是  yolov3 版本么？我这边不能用YoloV5Translator 这样用得意思？

**Comment by gengyanlei** [comment]
yolov5的第3版本！

**Comment by javadoge** [comment]
谢谢
