### ISSUE TITLE
Improving Map

### ISSUE THREAD

**Issue by FarhanLhant** [gengyanlei/fire-smoke-detect-yolov4#47]
Excuse me, i already train my weight using yoloV4 configuration from alexey and some augmentation data like rotate, brightness contrast, etc and have running about 6000 iteration but only got Map around 65% when using your dataset , when i see your weight you have Map around 75% could you please tell me what data augmentation are you using or what hyperparameter and augmentation best for this case , thanks

**Comment by gengyanlei** [comment]
@FarhanLhant 
The amount of data I use is more, about 6000 images. So, the effect is better.
All other parameters are default. The data I shared is the data that was marked for the first time. After collecting data continuously, and changing some marking rules, the effect will be better.

**Comment by FarhanLhant** [comment]
ahh I see thanks for your explanation sir
